function allocation_priority (input) {
    let i, sum = 0;

    const symptoms = {
        "red_sore_around_nose": 7,
        "fast_heart_rate": 10,
        "weight_gain": 5,
        "spinning_movements": 6,
        "cough": 9,
        "loss_of_appetite": 7,
        "weakness_of_one_body_side": 9,
        "muscle_weakness": 8,
        "diarrhoea": 8,
        "pain_during_bowel_movements": 8,
        "cold_hands_and_feets": 2,
        "sinus_pressure": 3,
        "yellowing_of_eyes": 9,
        "dizziness": 8,
        "swollen_extremeties": 9,
        "dark_urine": 9,
        "anxiety": 3,
        "knee_pain": 3,
        "vomiting": 9,
        "stomach_pain": 7,
        "breathlessness": 8,
        "excessive_hunger": 9,
        "mood_swings": 3,
        "blister": 8,
        "rusty_sputum": 9,
        "pain_in_anal_region": 9,
        "blurred_and_distorted_vision": 9,
        "mucoid_sputum": 6,
        "irritability": 9,
        "cramps": 8,
        "restlessness": 6,
        "irregular_sugar_level": 9,
        "painful_walking": 6,
        "hip_joint_pain": 5,
        "swelling_of_stomach": 8,
        "red_spots_over_body": 9,
        "continuous_sneezing": 5,
        "weakness_in_limbs": 9,
        "small_dents_in_nails": 5,
        "prominent_veins_on_calf": 9,
        "skin_rash": 9,
        "back_pain": 2,
        "dehydration": 8,
        "high_fever": 7,
        "ulcers_on_tongue": 4,
        "constipation": 4,
        "watering_from_eyes": 9,
        "stomach_bleeding": 9,
        "spotting_urination": 1,
        "sunken_eyes": 3,
        "bloody_stool": 9,
        "receiving_unsterile_injections": 9,
        "bruising": 4,
        "lack_of_concentration": 3,
        "joint_pain": 4,
        "shivering": 3,
        "silver_like_dusting": 5,
        "internal_itching": 5,
        "mild_fever": 2,
        "swollen_legs": 9,
        "swollen_blood_vessels": 8,
        "bladder_discomfort": 8,
        "foul_smell_of_urine": 9,
        "acute_liver_failure": 1,
        "extra_marital_contacts": 2,
        "toxic_look_(typhos)": 9,
        "increased_appetite": 8,
        "obesity": 5,
        "runny_nose": 2,
        "lethargy": 7,
        "brittle_nails": 5,
        "yellow_urine": 9,
        "muscle_wasting": 8,
        "nausea": 8,
        "unsteadiness": 6,
        "patches_in_throat": 8,
        "slurred_speech": 9,
        "polyuria": 9,
        "fluid_overload": 8,
        "chest_pain": 1,
        "visual_disturbances": 9,
        "blood_in_sputum": 9,
        "movement_stiffness": 4,
        "itching": 2,
        "irritation_in_anus": 7,
        "distention_of_abdomen": 3,
        "indigestion": 3,
        "receiving_blood_transfusion": 5,
        "passage_of_gases": 7,
        "palpitations": 8,
        "malaise": 7,
        "coma": 1,
        "scurring": 7,
        "muscle_pain": 3,
        "abnormal_menstruation": 9,
        "stiff_neck": 3,
        "loss_of_smell": 8,
        "burning_micturition": 9,
        "swelled_lymph_nodes": 9,
        "inflammatory_nails": 4,
        "weight_loss": 7,
        "family_history": 2,
        "nodal_skin_eruptions": 6,
        "blackheads": 5,
        "fatigue": 4,
        "history_of_alcohol_consumption": 3,
        "redness_of_eyes": 9,
        "sweating": 9,
        "swelling_joints": 5,
        "pus_filled_pimples": 3,
        "abdominal_pain": 7,
        "yellowish_skin": 8,
        "enlarged_thyroid": 9,
        "neck_pain": 3,
        "altered_sensorium": 8,
        "belly_pain": 7,
        "phlegm": 9,
        "dischromic_patches": 7,
        "pain_behind_the_eyes": 8,
        "skin_peeling": 7,
        "continuous_feel_of_urine": 9,
        "drying_and_tingling_lips": 7,
        "throat_irritation": 6,
        "acidity": 2,
        "chills": 3,
        "congestion": 8,
        "puffy_face_and_eyes": 9,
        "loss_of_balance": 6,
        "depression": 5,
        "yellow_crust_ooze": 7,
        "headache": 7
    };

    const ob = new Map(Object.entries(symptoms));

    for (i = 0; i < input.length; i++) {
        sum += ob.get(input[i]); 
    }

    console.log("Weighted Sum = ", sum);

    if (sum >= 10) {
        return "High";
    } else if (sum > 7 && sum < 10) {
        return "Medium";
    } else {
        return "Low";
    }
}

module.exports = { allocation_priority }; 
